# Site
repository: unknown parameter1
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Thorsten Eicheldinger
title: Junior software developer
email: teicheld@web.de
website: www.github.com/teicheld

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  teicheld
stackoverflow_username: "16086950"
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: blabalbalbla
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Thorsten and I'm a junior software developer and student at Codam.nl where I am gaining teamwork and leadership skills.

  Expertise: <mark>C</mark> <mark>Linux</mark> <mark>Shell</mark> <mark>Java</mark>



content:
  - title: Project # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: real-time map analysis
        link: https://github.com/teicheld/realtimeStreamFS
        # link_text: Project Website
        #        additional_links:
        #          - title:  sproogen/modern-resume-theme
        #            icon: fab fa-github
        #            url: github.com/sproogen/modern-resume-theme
        #          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #          #   icon: fab fa-github
        #          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
                Coding in a team under time pressure got me thinking afterwards about priority and time management.
        description: | # this will include new lines to allow paragraphs
          This was my first hackerton, hosted at the school 42 in Amsterdam. I have developed the project with one peer over 3 days.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: selfstuding
        link: github.com/eicheld
        # link_text: boringcompany.com
        sub_title: C
        caption: November 2020 - now
        quote: >
          Learning all the keywords and the syntax in C was interesting. Solving problems in C was hard and fun like math.
        description: | # this will include new lines to allow paragraphs
            We all go the same path of learning programming together, push and review each other.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in electronics and software engineering some of my other interests and hobbies are:
      - Sailing
      - Gaming
      - Camping

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
