# Site
repository: unknown parameter1
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Thorsten Eicheldinger
title: Junior software developer
email: teicheld@web.de
website: www.github.com/teicheld

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  teicheld
stackoverflow_username: "16086950"
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: blabalbalbla
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Thorsten and I'm a junior software developer with 2 years experience.
  I am currently student at Codam a school in Amsterdam.
  I enjoy learning since I have more projects in my mind as time to realise them. I am always searching for opportunities to work with something new. The topics in which I have the most experience working with are
  <mark>C</mark>(5 months),
  <mark>Linux</mark>(2 years), 
  <mark>Shell</mark>(2 years), 
  <mark>PHP</mark>(3 months), 
  <mark>MySQL</mark>(3 months), 
  <mark>git</mark>(2 months), 
  <mark>Java</mark>(currently learning)

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        title: real-time map analysis
        additional_links:
          - title: github
            icon: fab fa-github
            url: https://github.com/teicheld/realtimeStreamFS
        #        additional_links:
        #          - title:  sproogen/modern-resume-theme
        #            icon: fab fa-github
        #            url: github.com/sproogen/modern-resume-theme
        #          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #          #   icon: fab fa-github
        #          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
                Coding in a team under time pressure got me thinking afterwards about priority and time management.
        description: | # this will include new lines to allow paragraphs
                This was my first hackerton, hosted at the school 42 in Amsterdam. I have developed the project with one peer over 3 days. It is written in C.

      - layout: top-left
        title: A marketplace as webservice
        link: http://216.24.253.6
        link_text: website
        additional_links:
          - title: github
            icon: fab fa-github
            url: https://github.com/teicheld/GeoCamar
        #       additional_links:
        #         - title:  geocaching_market
        #           icon: fab fa-github
        #           url: https://github.com/teicheld/GeoCamar
        #          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #          #   icon: fab fa-github
        #          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
                I learned php and html and built it from ground up. Everytime after implementing successful a new feature I felt great. 
        description: | # this will include new lines to allow paragraphs
                This is the resultat of my html, css, php, mysql learning session

  - title: My experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
        - layout: left
          title: GNU Linux and Bash
          link: github.com/teicheld/
          quote: >
            You can do almost anything with the GNU-Utils and the BASH command language.
          description: | # this will include new lines to allow paragraphs
            I decided to become a programer two years ago. Through the effort of understanding and maintaining the GNU software and the Linux system I did a deep dive into the BASH command language. After feeling comfortable automating my daily tasks, I was ready to go a step further learning to realise my idea of building a open marketplace...

        - layout: right
          title: The Marketplace
          link: http://216.24.253.6
          quote: > 
            The experience and mindset which a gained during develpment was it worth, even if I changed the model of my application at the end fundamental.
            
          description: | # this will include new lines to allow paragraphs
                  As the frame was implemented I had thought already alot about security. I read the Bitcoin whitepaper and was impressed how simple and effective it was and how completly different it was compared to the traditional client-server model which I had in focus. I decided to focus on a decentraliced model to become sustainable as bitcoin and quit development on this version. But still I cant keep my hands complete away, because I like what I have built so far. I set it online for demonstration purposes. It was time to go on further with something else. Something like C...

        - layout: left
          title: The C programming language
          link: https://github.com/teicheld/learning_the_c_language
          quote: > 
            If you know C you know what is happening under the hood of high-level languages.
          description: | # this will include new lines to allow paragraphs
                  I learnd each keyword and the syntax of the language by solving related problems until I had gone through them all. After that I was accepted at the coding college "Codam" in Amsterdam. Suprising for me was how rigorous our programs are penetrated so I begon to think about harden my code against edge cases. A new value to which I was gratefuly exposed was the value of peer reviews. Reading somebody elses code and explaining my own raises your learning curve. Since then I am community focused. 

        - layout: right
          title: Where does my path go?
          quote: > 
            You can have an impact on my future path.
          description: | # this will include new lines to allow paragraphs
                  At Codam I can choose my path out of comprehensive resources. As you have read until here, I am definitely interested in your company and I appreciate to hear from you.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in electronics and software engineering some of my other interests and hobbies are:
      - Sailing
      - Gaming
      - Camping

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
