# Site
repository: unknown parameter1
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Thorsten Eicheldinger
title: Junior software developer
email: teicheld@web.de
website: www.github.com/teicheld

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  teicheld
stackoverflow_username: "16086950"
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: blabalbalbla
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: > # this will include new lines to allow paragraphs
  Hello, my name is Thorsten and I'm a junior software developer with 2 years experience.
  I am currently enrolled in a computer science education program in germany and am searching for opportunities to work with. 
  The topics in which I have the most experience working with are
  <mark>C</mark>(5 months),
  <mark>Linux</mark>(3 years), 
  <mark>PHP</mark>(3 months), >
  <mark>MySQL</mark>(3 months), >
  <mark>git</mark>(5 months), >
  <mark>Java</mark>(4 months)>
  <mark>Python</mark>(currently learning)

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-left
        title: real-time map analysis
        additional_links:
          - title: github
            icon: fab fa-github
            url: https://github.com/teicheld/realtimeStreamFS
        #        additional_links:
        #          - title:  sproogen/modern-resume-theme
        #            icon: fab fa-github
        #            url: github.com/sproogen/modern-resume-theme
        #          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #          #   icon: fab fa-github
        #          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
                Coding in a team under time pressure got me thinking afterwards about priority and time management.
        description: | # this will include new lines to allow paragraphs
                This was my first hackerton. I have developed the project with one peer over 3 days. It is written in C.

  - title: My experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
        - layout: left
          title: GNU Linux and Bash
          additional_links:
            - title: github
              icon: fab fa-github
              url: https://github.com/teicheld?tab=repositories&q=&type=&language=shell&sort=
          quote: >
            You can do almost anything with the GNU-Utils and the BASH command language.
          description: | # this will include new lines to allow paragraphs
            I decided to become a programer a few years ago. Through the effort of understanding and maintaining the GNU software and the Linux system I did a dive into the BASH scripting language.

            
        - layout: left
          title: The C programming language
          additional_links:
            - title: github
              icon: fab fa-github
              url: https://github.com/teicheld/learning_the_c_language

          quote: > 
            If you know C you know what is happening under the hood of high-level languages.
          description: | # this will include new lines to allow paragraphs
                  I learnd each keyword and the syntax of the language by solving related problems until I had gone through them all. After this I practised through pair programming to deepen skills. Suprising for me was how rigorous our programs are penetrated so I begon to think about harden my code against edge cases. A new value to which I was gratefuly exposed was the value of peer reviews. Reading somebody elses code and explaining my own raised my learning curve.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in electronics and software engineering some of my other interests and hobbies are:
      - Sailing
      - Science fiction
      - Libertarianism

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
