# Site
repository: unknown parameter1
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Thorsten Eicheldinger
title: Junior software developer
email: teicheld@web.de
website: www.github.com/teicheld

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username:  teicheld
stackoverflow_username: "16086950"
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: blabalbalbla
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: https://i.stack.imgur.com/5uY8f.jpg?s=256&g=1
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Thorsten and I'm a junior software developer and student at Codam.nl where I am gaining teamwork and leadership skills.

  I am most skilled in: <mark>C> and <mark>Linux</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: I have no cool Project to present
        link: github.com/teicheld
        # link_text: Project Website
        #        additional_links:
        #          - title:  sproogen/modern-resume-theme
        #            icon: fab fa-github
        #            url: github.com/sproogen/modern-resume-theme
        #          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #          #   icon: fab fa-github
        #          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          I have no cool project to present, because I am focusing on my own and not on buisness problems.
        description: | # this will include new lines to allow paragraphs
         In the future I am creating a <mark>Bugtracker</mark>. I have learned many skills through selfstudiyng.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: selfstuding
        link: github.com/eicheld
        # link_text: boringcompany.com
        sub_title: C
        caption: November 2019 - February 2020
        quote: >
          Learning all the keywords and the syntax in C was *intersting. Solving problems in C was hard and fun like math.
        description: | # this will include new lines to allow paragraphs
            We all go the same path of learning programming together, push and review each other.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: I have no certificated education and was wasting my time in school.
        caption: 2000 - 2019
        sub_title: fuck the state and my parents
        quote: >
                I like bushcraft, because this is all I have left in this fucking society.
        description: | # this will include new lines to allow paragraphs
          During my time after school I learnt most of my skills in electronic and coding. I expanded during my career this skills through abilities like teamwork and working to tight deadlines. I thouroughly enjoyed my free time outside of official education and learnd a lot there about healthy work life balance.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in electronics and software engineering some of my other interests and hobbies are:
      - Sailing
      - Gaming
      - Camping

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
